defaults:
  - _self_
  
# Data settings
data:
  h5_file: "/home/users/li1995/global_flood/FloodRisk-DL/src/data_preparation/flood_data.h5"  # Path to the H5 dataset
  batch_size: 8
  num_workers: 4
  
# Model settings
model:
  name: "swin_transformer"
  img_size: 1024  # Target image size
  patch_size: 4
  in_channels: 2  # DEM and rainfall
  embed_dim: 96
  depths: [2, 2, 6, 2]
  num_heads: [3, 6, 12, 24]
  window_size: 8
  mlp_ratio: 4.0
  drop_rate: 0.1
  attn_drop_rate: 0.0
  drop_path_rate: 0.1
  
# Training settings
training:
  max_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.05
  lr_scheduler: "plateau"
  # warmup_epochs: 5
  
# Logging settings
logging:
  project_name: "UrbanFlood2D"
  log_every_n_steps: 10
  save_top_k: 1
  monitor: "val_loss"
  mode: "min" 