defaults:
  - _self_
  
# Data settings
data:
  data_dir: "/home/users/li1995/global_flood/FloodRisk-DL/src/data_preparation"  # Path to the H5 dataset
  batch_size: 4
  num_workers: 3
  image_size: 512
  num_images: 400
  lulc: True
  
# Model settings
model:
  in_channels: 2  # DEM and rainfall
  ## This configuration for SWIN transformer
  #name: "swin"
  #patch_size: 4
  #embed_dim: 96
  #num_layers: 3
  #num_heads: 8
  #window_size: 16
  #mlp_ratio: 4.0
  #drop_rate: 0.1
  #attn_drop_rate: 0.0
  #drop_path_rate: 0.1
  ## This configuration for UNET
  #name: "unet"
  #filters: [64, 128, 256, 512]
  #droup_rate: 0.1

  #name: "diffusion"
  #layers_per_block: 2
  #block_out_channels: [128, 128, 256, 256, 512, 512]
  #timestep: 1000

  name: "segmentation"
  backbone: "resnet50"
  pretrained: True
  
# Training settings
training:
  max_epochs: 500
  learning_rate: 0.001
  accumulate_grad_batches: 8
  weight_decay: 0.05
  lr_scheduler: "LinearWarmupCosineAnnealingLR"
  warmup_epochs: 5
  maxepochs: 50
  warmuplr: 1e-6
  etamin: 1e-6
  checkpoint: 
  
  
# Logging settings
logging:
  checkpoints_dir: "checkpoints/UnetDiffusion"
  project_name: "UrbanFlood2D"
  run_name: "Diffusion-lr1e-4"
  log_every_n_steps: 10
  save_top_k: 1
  monitor: "val_loss"
  mode: "min" 