defaults:
  - _self_
  
# Data settings
data:
  data_dir: "/home/users/li1995/global_flood/FloodRisk-DL/src/data_preparation"  # Path to the H5 dataset
  batch_size: 4
  num_workers: 8
  
# Model settings
model:
  # name: "swin_transformer"
  name: "cnn"
  img_size: 1024  # Target image size
  in_channels: 2  # DEM and rainfall
  ## This configuration for SWIN transformer
  # patch_size: 4
  # embed_dim: 96
  # num_layers: 3
  # num_heads: 8
  # window_size: 16
  # mlp_ratio: 4.0
  # drop_rate: 0.1
  # attn_drop_rate: 0.0
  # drop_path_rate: 0.1
  ## This configuration for UNET
  filters: [64, 128, 256, 512]
  droup_rate: 0.1
  
# Training settings
training:
  max_epochs: 500
  learning_rate: 0.0001
  accumulate_grad_batches: 8
  weight_decay: 0.05
  lr_scheduler: "LinearWarmupCosineAnnealingLR"
  warmup_epochs: 5
  maxepochs: 50
  warmuplr: 1e-6
  etamin: 1e-6
  checkpoint: 
  
  
# Logging settings
logging:
  project_name: "UrbanFlood2D"
  run_name: "CNN-lr1e-4"
  log_every_n_steps: 10
  save_top_k: 1
  monitor: "val_loss"
  mode: "min" 