defaults:
  - _self_
  
# Data settings
data:
  data_dir: "/home/users/li1995/global_flood/FloodRisk-DL/src/data_preparation"  # Path to the H5 dataset
  batch_size: 16
  num_workers: 8
  
# Model settings
model:
  name: "swin_transformer"
  img_size: 1024  # Target image size
  patch_size: 4
  in_channels: 2  # DEM and rainfall
  embed_dim: 96
  num_layers: 3
  num_heads: 8
  window_size: 16
  mlp_ratio: 4.0
  drop_rate: 0.1
  attn_drop_rate: 0.0
  drop_path_rate: 0.1
  
# Training settings
training:
  max_epochs: 500
  learning_rate: 0.0005
  accumulate_grad_batches: 8
  weight_decay: 0.05
  lr_scheduler: "LinearWarmupCosineAnnealingLR"
  warmup_epochs: 5
  maxepochs: 50
  warmuplr: 1e-6
  etamin: 1e-6
  checkpoint: 
  
  
# Logging settings
logging:
  project_name: "UrbanFlood2D"
  log_every_n_steps: 10
  save_top_k: 1
  monitor: "val_loss"
  mode: "min" 